name: Deploy ETL

on:
  push:
    branches:
      - master

jobs:
  deploy_etl:
      runs-on: ubuntu-latest
      timeout-minutes: 20

      steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: master

      # Copy Config
      - name: Copy Config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key : ${{ secrets.SERVER_PRIVATE }}
          source: "./"
          target: "./etl"
          rm: false
          
      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key : ${{ secrets.SERVER_PRIVATE }}
          script: |
            cd ./etl
            echo POSTGRES_PASSWORD="${{secrets.POSTGRES_PASSWORD}}" > .env
            echo POSTGRES_HOST="postgres" >> .env
            docker-compose up -d --no-deps --build --force-recreate